services:
  app:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./authentification.env
    environment:
      FLASK_ENV: docker
    volumes:
      - ./application:/app
    command: python run.py
    depends_on:
      - db
    networks:
      - app_network

  db:
    container_name: mariadb_cont
    build:
      context: ./mariadb-docker
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./authentification.env
    environment:
       MARIADB_ROOT_PASSWORD: root
       MARIADB_DATABASE: annuaires_student
       MARIADB_USER: edmond
       MARIADB_PASSWORD: adams001
    ports:
      - "3306:3306"
    volumes:
      - ./my.cnf:/etc/mysql/my.cnf
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:

volumes:
  db_data:
